### ISSUE TITLE
Include Sentry for bug catching

### ISSUE THREAD

**Issue by stevepeak** [asyncy/platform-hub#2]
The easiest way to load Raven.js is to load it directly from our CDN. This script tag should be included after other libraries are loaded, but before your main application code (e.g. app.js):

```html
<script src="https://cdn.ravenjs.com/3.25.1/raven.min.js" crossorigin="anonymous"></script>
```

Configuring the Client
Next you need to configure Raven.js to use your Sentry DSN:

```js
Raven.config('https://93f5d14ba8eb424d903a1a0881d1fa6d@sentry.io/1206503').install()
```
> The configuration url should be an environment variable in Netlify.

It is additionally recommended (but not required) to wrap your application start using Raven.context. This can help surface additional errors in some execution contexts.

```js
Raven.context(function () {
    initMyApp();
});
```

**Comment by abylaw** [comment]
@stevepeak Could I get temporary access to the Sentry dashboard to make sure things are working?

**Comment by stevepeak** [comment]
@abylaw All set, thanks
