### ISSUE TITLE
Services do not load in mobile

### ISSUE THREAD

**Issue by stevepeak** [asyncy/platform-hub#4]
The Hub loads services in desktop but is empty in mobile (tested on iPhone, iPad)

**Comment by abylaw** [comment]
Hey @stevepeak. This issue should be fixable using by whitelisting `Content-Type` in `Access-Control-Allow-Headers` (note: Allow-Headers, not Request-Headers) on the GraphQL server. The precise header used seems to be os/browser specific.

**Comment by abylaw** [comment]
Seems like Safari requires you to explicitly whitelist the headers - so in this case, we need to configure `Access-Control-Allow-Headers` to include `Content-Type` (should not be case-sensitive).

**Comment by stevepeak** [comment]
Looks like that worked 👍
