### ISSUE TITLE
Add Algolia search

### ISSUE THREAD

**Issue by stevepeak** [asyncy/platform-hub#9]
<img width="568" alt="screen shot 2018-08-17 at 09 59 53" src="https://user-images.githubusercontent.com/2041757/44254830-525a0400-a204-11e8-8c47-e6a301425634.png">

- Add Algolia search
- Research how Algolia can index the services and all commands/arguments, etc.

**Comment by romucci** [comment]
Are you looking for an implementation of an algolia-type-search? 

or just plainly pay for algolia? 🍡

**Comment by stevepeak** [comment]
Will use our own internal searching instead.
